namespace JunkCodeGeneratorApp.src
{ 
    static public class Placeholders
    {
        public const string RANDOM_STRING_VALUE = "RANDOM_STRING_VALUE";
        public const string RANDOM_INT_VALUE = "RANDOM_INT_VALUE";
        public const string RANDOM_BYTE_VALUE = "RANDOM_BYTE_VALUE";
        public const string RANDOM_DECIMAL_VALUE = "RANDOM_DECIMAL_VALUE";
        public const string RANDOM_STRING_ARRAY_VALUE = "RANDOM_STRING_ARRAY_VALUE";
        public const string RANDOM_INT_ARRAY_VALUE = "RANDOM_INT_ARRAY_VALUE";
        public const string RANDOM_BYTE_ARRAY_VALUE = "RANDOM_BYTE_ARRAY_VALUE";
        public const string RANDOM_DECIMAL_ARRAY_VALUE = "RANDOM_DECIMAL_ARRAY_VALUE";

        public const string VAR_VARIABLE_RAND_DECLARATION = "VAR_VARIABLE_RAND_DECLARATION";
        public const string STRING_VARIABLE_RAND_DECLARATION = "STRING_VARIABLE_RAND_DECLARATION";
        public const string INT_VARIABLE_RAND_DECLARATION = "INT_VARIABLE_RAND_DECLARATION";
        public const string BYTE_VARIABLE_RAND_DECLARATION = "BYTE_VARIABLE_RAND_DECLARATION";
        public const string DECIMAL_VARIABLE_RAND_DECLARATION = "DECIMAL_VARIABLE_RAND_DECLARATION";
        public const string STRING_ARRAY_VARIABLE_RAND_DECLARATION = "STRING_ARRAY_VARIABLE_RAND_DECLARATION";
        public const string INT_ARRAY_VARIABLE_RAND_DECLARATION = "INT_ARRAY_VARIABLE_RAND_DECLARATION";
        public const string BYTE_ARRAY_VARIABLE_RAND_DECLARATION = "BYTE_ARRAY_VARIABLE_RAND_DECLARATION";
        public const string DECIMAL_ARRAY_VARIABLE_RAND_DECLARATION = "DECIMAL_ARRAY_VARIABLE_RAND_DECLARATION";

        public const string RANDOM_MATH_EXPRESSION = "RANDOM_MATH_EXPRESSION";
        public const string RANDOM_VARIABLE_DECLARATION_EXPRESSION = "RANDOM_VARIABLE_DECLARATION_EXPRESSION";

        public static string[] PlaceholdersArray = new string[]
        {
            RANDOM_STRING_VALUE,
            RANDOM_INT_VALUE,
            RANDOM_BYTE_VALUE,
            RANDOM_DECIMAL_VALUE,
            RANDOM_STRING_ARRAY_VALUE,
            RANDOM_INT_ARRAY_VALUE,
            RANDOM_BYTE_ARRAY_VALUE,
            RANDOM_DECIMAL_ARRAY_VALUE,
            VAR_VARIABLE_RAND_DECLARATION,
            STRING_VARIABLE_RAND_DECLARATION,
            INT_VARIABLE_RAND_DECLARATION,
            BYTE_VARIABLE_RAND_DECLARATION,
            DECIMAL_VARIABLE_RAND_DECLARATION,
            STRING_ARRAY_VARIABLE_RAND_DECLARATION,
            INT_ARRAY_VARIABLE_RAND_DECLARATION,
            BYTE_ARRAY_VARIABLE_RAND_DECLARATION,
            DECIMAL_ARRAY_VARIABLE_RAND_DECLARATION,
            RANDOM_MATH_EXPRESSION,
            RANDOM_VARIABLE_DECLARATION_EXPRESSION,
        };
    }
}
